name: Bug report
description: Report a reproducible problem or regression
title: '[Bug]: '
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug report. Please include enough detail to reproduce the issue.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and what you expected instead.
      placeholder: A clear and concise description of the problem.
    validations:
      required: true
  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      description: Provide a minimal, reliable reproduction.
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: amazon_domain
    attributes:
      label: Amazon domain
      description: Which Amazon site were you using?
      placeholder: 'e.g. amazon.com, amazon.de, amazon.co.uk'
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Firefox
        - Chrome
        - Edge
        - Brave
        - Other
    validations:
      required: true
  - type: input
    id: extension_version
    attributes:
      label: Extension version
      placeholder: 'e.g. 1.2.3'
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Paste errors from browser devtools console if available.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: I can reproduce this issue on the latest release.
          required: true
