name: Feature request
description: Suggest an improvement or new capability
title: '[Feature]: '
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please describe the problem and expected outcome clearly.
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What pain point are you experiencing?
      placeholder: A clear and concise description of the current limitation.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the behavior you want.
      placeholder: What should change, and how should it work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches you considered.
      placeholder: Optional
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Use cases, examples, links, or screenshots.
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
